name: walkthrux
description: "Advanced, customizable onboarding and showcase package for flutter with multi-screen walkthrough, smart targeting, analytics, and accessibility features."
publish_to: 'none'
version: 0.1.0
homepage: https://github.com/praveenaththanayake/walkthrux

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_tts: ^4.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
